
version: '3.8'



services:

  postgres:

    image: postgres:15-alpine

    container_name: gramchat-postgres

    environment:

      POSTGRES_DB: gramchat_db

      POSTGRES_USER: gramchat

      POSTGRES_PASSWORD: gramchat_password

    ports:

      - "5432:5432"

    volumes:

      - postgres-data:/var/lib/postgresql/data

    healthcheck:

      test: ["CMD-SHELL", "pg_isready -U gramchat"]

      interval: 10s

      timeout: 5s

      retries: 5



  redis:

    image: redis:7-alpine

    container_name: gramchat-redis

    ports:

      - "6379:6379"

    volumes:

      - redis-data:/data

    command: redis-server --appendonly yes

    healthcheck:

      test: ["CMD", "redis-cli", "ping"]

      interval: 10s

      timeout: 5s

      retries: 5



  adminer:

    image: adminer

    container_name: gramchat-adminer

    ports:

      - "8080:8080"

    environment:

      ADMINER_DEFAULT_SERVER: postgres

    depends_on:

      - postgres



volumes:

  postgres-data:

  redis-data:

