#!/bin/bash

echo "================================================"
echo "ОБНОВЛЕНИЕ EXPRESS НА СЕРВЕРЕ"
echo "================================================"
echo ""
echo "Выполните эти команды на сервере в SSH терминале:"
echo ""
echo "cd /var/www/gramchat"
echo ""
echo "# Обновляем код из GitHub"
echo "git pull"
echo ""
echo "# Обновляем зависимости backend"
echo "cd backend"
echo "npm install"
echo "cd .."
echo ""
echo "# Пересобираем backend контейнер"
echo "docker-compose -f docker-compose.production.yml stop backend"
echo "docker-compose -f docker-compose.production.yml rm -f backend"
echo "docker-compose -f docker-compose.production.yml build --no-cache backend"
echo "docker-compose -f docker-compose.production.yml up -d backend"
echo ""
echo "# Проверяем логи"
echo "docker-compose -f docker-compose.production.yml logs -f backend"
echo ""
echo "================================================"
echo "После обновления проверьте работу авторизации"
echo "на https://web.gramchat.ru"
echo "================================================"